---
title: "ETM 537/506 Course Project"
author: "Kamal Thapa"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note: Data Available from 2017-18 to 2022-23.

# 2022-2023 Data Processing

Load required packages for data processing.

```{r load_library, echo=FALSE, warning = FALSE}

library(readxl)  #package for excel
library(readr)   #package for csv
library(dplyr)   #package for data manipulation
library(stringr) #package for string manipulation

```

```{r free_lunch_data_2223, echo=FALSE}

library(readxl)

# path of the Excel file
excel_path1 <- "Raw Data/2023RM.xlsx"


# Read the first sheet of the Excel file 
sheet_name1 <- excel_sheets(excel_path1)[1]  # Get the name of the first sheet
data1 <- read_excel(excel_path1, sheet = sheet_name1)

```

```{r convert_dataframe_2223, echo=FALSE}

data1_df <- as.data.frame(data1)
colnames(data1_df) <- NULL
data1_df

```

```{r data_cleaning_2223, echo=FALSE}

# assign column names
colnames(data1_df) <- data1_df[1,]

# delete first and last rows which are unnecessary
meal_data_df <- data1_df[-1,]

meal_data_df

```



```{r expense_process_2223, echo=FALSE}

library(dplyr)

select_data1 <- as.data.frame(meal_data_df) |> #convert to dataframe
  select("Sponsor Name", "Site Name", "Site Number", "Percent Eligible")   #selects the columns
  

select_data1 <- select_data1 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, 
         "SNo"=`Site Number`,"LunchRPer"="Percent Eligible") |> #renames to eliminate spaces
  arrange(School) #arrange in alphabetical order based on School Column
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

filtered_data1 <- select_data1 |>
  filter(grepl("Beaverton SD 48J", `District`, ignore.case = TRUE) &
           !grepl(paste(keywords1, collapse = "|"), `School`, ignore.case = TRUE)) 
# concatenate the elements of the keywords1 vector into a single string, where the elements are separated by the | 
#filters out the keywords

filtered_data1


```


```{r free_differentiate_Raleighs_2223}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data1$School[filtered_data1$School == "Raleigh Hills Elem"] <- "RaleighHills Elem" #checks value in column and replaces 
filtered_data1$School[filtered_data1$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"  #checks value in column and replaces 

filtered_data1


```



```{r school_names_2223, echo=FALSE}

library(dplyr)
library(stringr)

original_school_names <- filtered_data1[2]

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))

# Add the number 2223 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "2223")

# To access the new variable:
schoolname2223 <- as.data.frame(new_data$FirstWord)

colnames(schoolname2223) <- c("School")

```


```{r lunch_colbind_2223, echo=FALSE}

lunch_data2223 <- cbind(schoolname2223,filtered_data1[4])
lunch_data2223

```


# 2021-2022

```{r free_meal_data_2122, echo=FALSE}

library(readxl)

# URL of the Excel file
url2 <- "https://www.oregon.gov/ode/reports-and-data/students/Documents/Free%20and%20Reduced%20Price%20School%20Data%202021.xlsx"

# Download the file to a temporary location 
temp_file2 <- tempfile()
download.file(url2, temp_file2, mode = "wb")

# Read the first sheet of the Excel file from the temporary location
sheet_name2 <- excel_sheets(temp_file2)[1]  # Get the name of the first sheet
data2 <- read_xlsx(temp_file2, sheet = sheet_name2)

# Remove the temporary file
file.remove(temp_file2)

```



```{r delete_2122}

print(data2)

```


```{r data_cleaning_2122, echo=FALSE}

# assign column names
colnames(data2) <- data2[2,]  # assings colnames based on second row


# delete first and second rows which are unnecessary
meal_data_df2 <- data2[-(1:2),]

meal_data_df2

```

```{r expense_process_2122, echo=FALSE}

library(dplyr)

select_data2 <- as.data.frame(meal_data_df2) |> #convert to dataframe
  select("Sponsor Name", "Site Name", "Percent Eligible")   #selects the columns
  

select_data2 <- select_data2 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, "LunchRPer"= `Percent Eligible`) |> #renames column 
  arrange(School) #arranges in alphabetical order based on School Column
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

filtered_data2 <- select_data2 |>
  filter(grepl("Beaverton SD 48J", `District`, ignore.case = TRUE) &
           !grepl(paste(keywords1, collapse = "|"), `School`, ignore.case = TRUE)) #filters out the keywords

filtered_data2


```

```{r free_differentiate_Raleighs_2122}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data2$School[filtered_data2$School == "Raleigh Hills Elem"] <- "RaleighHills Elem"
filtered_data2$School[filtered_data2$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"

filtered_data2


```



```{r school_names_2122, echo=FALSE}
# Assuming original_school_names is a data frame with a column named "School"
# If not, you should replace "School" with the actual column name in your data frame

library(dplyr)
library(stringr)

original_school_names <- filtered_data2[2] #extracts second column

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))

# Add the number 2122 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "2122")

# rename as dataframe
schoolname2122 <- as.data.frame(new_data$FirstWord)

colnames(schoolname2122) <- c("School")

```


```{r lunch_colbind_2122, echo=FALSE}

lunch_data2122 <- cbind(schoolname2122,filtered_data2[3])
lunch_data2122

```


# 2020-2021

```{r free_lunch_data_2021, echo=FALSE}

library(readxl)

# path of the Excel file
excel_path3 <- "Raw Data/2020RM.xlsx"

# Read the first sheet of the Excel file 
sheet_name3 <- excel_sheets(excel_path3)[1]  # Get the name of the first sheet
data3 <- read_excel(excel_path3, sheet = sheet_name3)

```

```{r convert_dataframe_2021, echo=FALSE}

data3_df <- as.data.frame(data3)
colnames(data3_df) <- NULL
data3_df

```

```{r data_cleaning_2021, echo=FALSE}


# delete first row which are unnecessary
meal_data_df3 <- data3_df[-1,]

colnames(meal_data_df3) <- c("County", "Sponsor Name", "Site Name", "Site Number","Percent Eligible")

meal_data_df3

```



```{r expense_process_2021, echo=FALSE}

library(dplyr)

select_data3 <- as.data.frame(meal_data_df3) |> #convert to dataframe
  select(`Sponsor Name`, `Site Name`, `Percent Eligible`)   #selects the columns
  

select_data3 <- select_data3 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, "LunchRPer"= `Percent Eligible`) |> #renames column Student 
  arrange(School) #arranges in alphabetical order 
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

filtered_data3 <- select_data3 |>
  filter(grepl("Beaverton SD 48J", `District`, ignore.case = TRUE) &
           !grepl(paste(keywords1, collapse = "|"), `School`, ignore.case = TRUE)) #filters out the keywords

filtered_data3


```

```{r free_differentiate_Raleighs_2021}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data3$School[filtered_data3$School == "Raleigh Hills Elem"] <- "RaleighHills Elem"
filtered_data3$School[filtered_data3$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"

filtered_data3


```



```{r school_names_2021, echo=FALSE}

library(dplyr)
library(stringr)

original_school_names <- filtered_data1[2]

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))


# Add the number 2021 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "2021")

# rename as dataframe
schoolname2021 <- as.data.frame(new_data$FirstWord)

colnames(schoolname2021) <- c("School")

```


```{r lunch_colbind_2021, echo=FALSE}

lunch_data2021 <- cbind(schoolname2021,filtered_data3[3])
lunch_data2021

```



# 2019-2020

```{r free_lunch_data_1920, echo=FALSE}

library(readxl)

# path of the Excel file
excel_path4 <- "Raw Data/2019RM.xlsx"

# Read the first sheet of the Excel file 
sheet_name4 <- excel_sheets(excel_path4)[1]  # Get the name of the first sheet
data4 <- read_excel(excel_path4, sheet = sheet_name4)

```

```{r convert_dataframe_1920, echo=FALSE}

data4_df <- as.data.frame(data4)
colnames(data4_df) <- NULL
data4_df

```

```{r data_cleaning_1920, echo=FALSE}

colnames(data4_df) <- c("County", "Sponsor Name", "Site Name", "Del", "Site Number","Percent Eligible")

data4_df

```



```{r expense_process_1920, echo=FALSE}

library(dplyr)

select_data4 <- as.data.frame(data4_df) |> #convert to dataframe
  select(`Sponsor Name`, `Site Name`, `Percent Eligible`)   #selects the columns
  

select_data4 <- select_data4 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, "LunchRPer"= `Percent Eligible`) |> #renames column 
  arrange(School) #arranges in alphabetical order based on School Column
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

filtered_data4 <- select_data4 |>
  filter(grepl("Beaverton SD 48J", `District`, ignore.case = TRUE) &
           !grepl(paste(keywords1, collapse = "|"), `School`, ignore.case = TRUE)) #filters out the keywords

filtered_data4


```

```{r free_differentiate_Raleighs_1920}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data4$School[filtered_data4$School == "Raleigh Hills Elem"] <- "RaleighHills Elem"
filtered_data4$School[filtered_data4$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"

filtered_data4


```




```{r school_names_1920, echo=FALSE}

library(dplyr)
library(stringr)

original_school_names <- filtered_data4[2]

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))

# Add the number 1819 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "1920")

# rename as dataframe
schoolname1920 <- as.data.frame(new_data$FirstWord)

colnames(schoolname1920) <- c("School")

```


```{r lunch_colbind_1920, echo=FALSE}

lunch_data1920 <- cbind(schoolname1920,filtered_data4[3])
lunch_data1920

```

# 2018-2019

```{r free_lunch_data_1819, echo=FALSE}

library(readxl)

# path of the Excel file
excel_path5 <- "Raw Data/2018RM.xlsx"


# Read the first sheet of the Excel file 
sheet_name5 <- excel_sheets(excel_path5)[1]  # Get the name of the first sheet
data5 <- read_excel(excel_path5, sheet = sheet_name5)

```

```{r convert_dataframe_1819, echo=FALSE}

data5_df <- as.data.frame(data5)
colnames(data5_df) <- NULL
data5_df

```

```{r data_cleaning_1819, echo=FALSE}

colnames(data5_df) <- c("County", "Sponsor Name", "Site Name", "Site Number","Percent Eligible")

data5_df

```



```{r expense_process_1819, echo=FALSE}

library(dplyr)

select_data5 <- as.data.frame(data5_df) |> #convert to dataframe
  select(`Sponsor Name`, `Site Name`, `Percent Eligible`)   #selects the columns
  

select_data5 <- select_data5 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, "LunchRPer"= `Percent Eligible`) |> #renames column 
  arrange(School) #arranges in alphabetical order 
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

filtered_data5 <- select_data5 |>
  filter(grepl("Beaverton SD 48J", `District`, ignore.case = TRUE) &
           !grepl(paste(keywords1, collapse = "|"), `School`, ignore.case = TRUE)) #filters out the keywords

filtered_data5


```

```{r free_differentiate_Raleighs_1819}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data5$School[filtered_data5$School == "Raleigh Hills Elem"] <- "RaleighHills Elem"
filtered_data5$School[filtered_data5$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"

filtered_data5


```



```{r school_names_1819, echo=FALSE}

library(dplyr)
library(stringr)

original_school_names <- filtered_data5[2]

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))

# Add the number 1819 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "1819")

# rename as dataframe
schoolname1819 <- as.data.frame(new_data$FirstWord)

colnames(schoolname1819) <- c("School")

```


```{r lunch_colbind_1819, echo=FALSE}

lunch_data1819 <- cbind(schoolname1819,filtered_data5[3])
lunch_data1819

```

# 2017-2018

```{r free_lunch_data_1718, echo=FALSE}

library(readxl)

# path of the Excel file
excel_path6 <- "Raw Data/2017RM.xlsx"

# Read the first sheet of the Excel file 
sheet_name6 <- excel_sheets(excel_path6)[1]  # Get the name of the first sheet
data6 <- read_excel(excel_path6, sheet = sheet_name6)

```

```{r convert_dataframe_1718, echo=FALSE}

data6_df <- as.data.frame(data6)
colnames(data6_df) <- NULL
data6_df

```

```{r data_cleaning_1718, echo=FALSE}

colnames(data6_df) <- c("County", "Sponsor Name", "Site Name", "Site Number","Percent Eligible")

data6_df

```



```{r lunch_process_1718, echo=FALSE}

library(dplyr)

select_data6 <- as.data.frame(data6_df) |> #convert to dataframe
  select(`Sponsor Name`, `Site Name`, `Site Number`,`Percent Eligible`)   #selects the columns
  

select_data6 <- select_data6 |>
  rename("District"=`Sponsor Name`, "School"=`Site Name`, "SNo"=`Site Number`,"LunchRPer"= `Percent Eligible`) |> #renames column 
  arrange(School) #arranges in alphabetical order based on School Column
  

keywords1 <- c("Middle", "High", "Kairos", "Charter", "Emerson", 
               "Metropolitan", "Roseway","Village", "Academy", "Online", 
               "International", "Technology", "Health", "Southridge" ) #same keyword

keywords2 <- c(11202, 11203, 11204, 11205, 14276, 11206, 11207, 11208, 11209, 11210,
               11211, 11212, 11213, 11214, 11215, 11216, 12776, 11217, 11218, 11219, 
               11220, 11221, 11222, 11223, 11224, 11225, 15965, 11533, 11226, 14521, 
               11227, 11228, 11229, 11230) # as it was not recognising County and Sponsor for Beaverton School Dist


filtered_data6 <- select_data6 |>
  filter(is.na(District) & # checks if the values in the District column are NA
           grepl(paste(keywords2, collapse = "|"), `SNo`, ignore.case = TRUE))
           

filtered_data6


```

```{r free_differentiate_Raleighs_1718}
# change "Raleigh Hills" to "RaleighHills" and "Raleigh Park" to "RaleighPark" in the "School" column
filtered_data6$School[filtered_data6$School == "Raleigh Hills Elem"] <- "RaleighHills Elem"
filtered_data6$School[filtered_data6$School == "Raleigh Park Elem"]  <- "ReleighPark Elem"

filtered_data6


```


```{r school_names_1718, echo=FALSE}

library(dplyr)
library(stringr)

original_school_names <- filtered_data6[2]

# Create a new variable with only the first word of each school name
new_data <- original_school_names |>
  mutate(FirstWord = word(School, 1, sep = " "))

# Add the number 1718 to each "School"
new_data$FirstWord <- paste0(new_data$FirstWord, "1718")

# rename as dataframe
schoolname1718 <- as.data.frame(new_data$FirstWord)

colnames(schoolname1718) <- c("School")

```


```{r lunch_colbind_1718, echo=FALSE}

lunch_data1718_temp <- cbind(schoolname1718,filtered_data6[4]) 

# Since there was no Sato School in 17-19 
sato_data <- c("Sato1718", 0)
lunch_data1718 <- rbind(lunch_data1718_temp,sato_data)

lunch_data1718 <- lunch_data1718 |>
  arrange(School)

lunch_data1718

```





```{r final_data_save, echo=FALSE}

meal_data_final_percent <- rbind(lunch_data1819, lunch_data2021, lunch_data2122)

# Save the data frame as a CSV file
write.csv(meal_data_final_percent, "Processed Data/FreeMealFinal.csv", row.names = FALSE)

# Save the dataframe to an R data file 
saveRDS(meal_data_final_percent, file = "Processed Data/FreeMealFinal.rds")

```